# Generated by Django 3.0.4 on 2020-03-21 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('expertise', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='_user_connections_+', to='backend.User')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('struggle', models.CharField(max_length=50)),
                ('date_decided', models.IntegerField()),
                ('scope_date', models.DateTimeField()),
                ('pay_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event_place', models.IntegerField()),
                ('partner_description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_jobs', to='backend.User')),
                ('tags', models.ManyToManyField(related_name='event_jobs', to='backend.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='attending', to='backend.User')),
                ('collaborators', models.ManyToManyField(related_name='collaborations', to='backend.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.User')),
                ('tags', models.ManyToManyField(related_name='events', to='backend.Tag')),
            ],
        ),
    ]
